apiVersion: v1
kind: Namespace
metadata:
  name: web
---
apiVersion: v1
kind: Namespace
metadata:
  name: auth
---
apiVersion: v1
kind: Namespace
metadata:
  name: cart
---
apiVersion: v1
kind: Namespace
metadata:
  name: social
---
apiVersion: v1
kind: Namespace
metadata:
  name: catalog
---
apiVersion: v1
kind: Namespace
metadata:
  name: quote
---
apiVersion: v1
kind: Namespace
metadata:
  name: purchasing
---
apiVersion: v1
kind: Namespace
metadata:
  name: infra
---
apiVersion: v1
kind: Pod
metadata:
  name: homepage-dev
  namespace: web
  labels:
    env: development
    dev-lead: Rajesh
    team: web
    application_type: ui
    release-version: "12.0"
spec:
  containers:
  - name: explorecalifornia
    image: machelix/explorecalifornia.com:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: homepage-staging
  namespace: web
  labels:
    env: staging
    team: web
    dev-lead: Rajesh
    application_type: ui
    release-version: "12.0"
spec:
  containers:
  - name: explorecalifornia
    image: machelix/explorecalifornia.com:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: homepage-prod
  namespace: web
  labels:
    env: production
    team: web
    dev-lead: Rajesh
    application_type: ui
    release-version: "12.0"
spec:
  containers:
  - name: explorecalifornia
    image: machelix/explorecalifornia.com:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: login-dev
  namespace: auth
  labels:
    env: development
    team: auth
    dev-lead: mia
    application_type: api
    release-version: "1.0"
spec:
  containers:
  - name: login
    image: machelix/nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: login-staging
  namespace: auth
  labels:
    env: staging
    team: auth
    dev-lead: mia
    application_type: api
    release-version: "1.0"
spec:
  containers:
  - name: login
    image: machelix/nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: login-prod
  namespace: auth
  labels:
    env: production
    team: auth
    dev-lead: mia
    application_type: api
    release-version: "1.0"
spec:
  containers:
  - name: login
    image: machelix/nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: cart-dev
  namespace: cart
  labels:
    env: development
    team: ecommerce
    dev-lead: bulbul
    application_type: api
    release-version: "1.0"
spec:
  containers:
  - name: cart
    image: machelix/nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: cart-staging
  namespace: cart
  labels:
    env: staging
    team: ecommerce
    dev-lead: bulbul
    application_type: api
    release-version: "1.0"
spec:
  containers:
  - name: cart
    image: machelix/nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: cart-prod
  namespace: cart
  labels:
    env: production
    team: ecommerce
    dev-lead: bulbul
    application_type: api
    release-version: "1.0"
spec:
  containers:
  - name: cart
    image: machelix/nginx:latest
---

apiVersion: v1
kind: Pod
metadata:
  name: social-dev
  namespace: social
  labels:
    env: development
    team: marketing
    dev-lead: bulbul
    application_type: api
    release-version: "2.0"
spec:
  containers:
  - name: social
    image: machelix/nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: social-staging
  namespace: social
  labels:
    env: staging
    team: marketing
    dev-lead: marketing
    application_type: api
    release-version: "1.0"
spec:
  containers:
  - name: social
    image: machelix/nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: social-prod
  namespace: social
  labels:
    env: production
    team: marketing
    dev-lead: marketing
    application_type: api
    release-version: "1.0"
spec:
  containers:
  - name: social
    image: machelix/nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: catalog-dev
  namespace: catalog
  labels:
    env: development
    team: ecommerce
    dev-lead: anu
    application_type: api
    release-version: "4.0"
spec:
  containers:
  - name: catalog
    image: machelix/nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: catalog-staging
  namespace: catalog
  labels:
    env: staging
    team: ecommerce
    dev-lead: anu
    application_type: api
    release-version: "4.0"
spec:
  containers:
  - name: catalog
    image: machelix/nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: catalog-prod
  namespace: catalog
  labels:
    env: production
    team: ecommerce
    dev-lead: anu
    application_type: api
    release-version: "4.0"
spec:
  containers:
  - name: catalog
    image: machelix/nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: quote-dev
  namespace: quote
  labels:
    env: development
    team: ecommerce
    dev-lead: amy
    application_type: api
    release-version: "2.0"
spec:
  containers:
  - name: quote
    image: machelix/nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: quote-staging
  namespace: quote
  labels:
    env: staging
    team: ecommerce
    dev-lead: amy
    application_type: api
    release-version: "2.0"
spec:
  containers:
  - name: quote
    image: machelix/nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: quote-prod
  namespace: quote
  labels:
    env: production
    team: ecommerce
    dev-lead: amy
    application_type: api
    release-version: "1.0"
spec:
  containers:
  - name: quote
    image: machelix/nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: ordering-dev
  namespace: purchasing
  labels:
    env: development
    team: purchasing
    dev-lead: gunn
    application_type: backend
    release-version: "2.0"
spec:
  containers:
  - name: ordering
    image: machelix/nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: ordering-staging
  namespace: purchasing
  labels:
    env: staging
    team: purchasing
    dev-lead: gunn
    application_type: backend
    release-version: "2.0"
spec:
  containers:
  - name: ordering
    image: machelix/nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: ordering-prod
  namespace: purchasing
  labels:
    env: production
    team: purchasing
    dev-lead: gunn
    application_type: backend
    release-version: "2.0"
spec:
  containers:
  - name: ordering
    image: machelix/nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: logger
  namespace: infra
  labels:
    env: production
    team: infrastructure
    dev-lead: pari
    application_type: backend
    release-version: "2.0"
spec:
  containers:
  - name: logger
    image: machelix/nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: monitor
  namespace: infra
  labels:
    env: production
    team: infrastructure
    dev-lead: pari
    application_type: backend
    release-version: "2.0"
spec:
  containers:
  - name: monitor
    image: machelix/nginx:latest
---