apiVersion: apps/v1
kind: Deployment
metadata:
  name: green
spec:
  selector:
    matchLabels:
      app: green
  replicas: 1
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
      - name: green
        image: machelix/explorecalifornia.com
        ports:
        - containerPort: 80
