apiVersion: apps/v1
kind: Deployment
metadata:
  name: pink
spec:
  selector:
    matchLabels:
      app: pink
  replicas: 2
  template:
    metadata:
      labels:
        app: pink
    spec:
      containers:
      - name: pink
        image: machelix/explorecalifornia.com
        ports:
        - containerPort: 80


